COLUMN_RENAME_MAPS = {
    "primary_a": {
        "Line#": "line_number",
        "Element (if app.)": "element",
        "Component": "component",
        "Quantity": "quantity",
        "TL#": "tl_number",
        "part#": "part_tag",
        "Item#": "material_type",
        "Item Description": "item_description",
        "Code": "code",
        "Designation": "designation",
        "Order#": "material_subtype",
        "W [mm]": "width",
        "H [mm]": "height",
        "L [mm]": "length",
        "Additional Info.": "additional_info",
        "Weight p/Unit": "weight_per_unit",
        "Weight Unit": "weight_unit",
        "Cost Unit": "cost_unit",
        "Cost p/Unit": "cost_per_unit",
        "Deliver To": "deliver_to",
        "Source From": "source_from",
        "Tot. Length [m]": "usage_quantity",
        "Tot. Surf. Area [ft²]": "finish_quantity",
        "Tot. Volume [BF]": "total_volume",
        "Tot. Weight [kg]": "total_weight",
        "Tot. Cost [CAD]": "total_cost",
    },
    "primary_b": {
        "Line#": "line_number",
        "Element (if app.)": "element",
        "Component": "component",
        "Quantity": "quantity",
        "RNo": "r_number",
        "part#": "part_tag",
        "Item#": "material_type",
        "Item Description": "item_description",
        "Order#": "material_subtype",
        "Designation": "designation",
        "T [mm]": "height",
        "W [mm]": "width",
        "L [mm]": "length",
        "Wg/rf": "weight_per_unit",
        "Wref": "weight_unit",
        "Unit": "cost_unit",
        "Pr/unit": "cost_per_unit",
        "Del": "deliver_to",
        "Src": "source_from",
        "Additional Info.": "additional_info",
        "Edge l [m]": "edge_length",
        "Single Part Area [ft²]": "part_area",
        "Lin.m [m]": "total_length",
        "Tot. Stock Area [ft²]": "usage_quantity",
        "Vol. [BF]": "total_stock_volume",
        "Wght [kg]": "total_stock_weight",
        "Tot. Stock Cost [CAD]": "total_stock_cost",
        "T.ed.l. [m]": "total_edge_length",
        "Tot. Part Area [ft²]": "finish_quantity",
        "T.vol [BF]": "total_volume",
        "Tot. Part Weight [kg]": "total_weight",
    },
    "secondary": {},
}

# primary_a and primary_b have been grouped into primary as they share a downstream schema and transform logic
REQUIRED_COLUMNS_AFTER_RENAME = {
    "primary": {
        "element",
        "quantity",
        "part_tag",
        "material_type",
        "designation",
        "material_subtype",
        "width",
        "height",
        "length",
        "additional_info",
        "usage_quantity",
        "finish_quantity",
    },
    "secondary": {},
}


NULLABLE_COLUMNS = {
    "primary": {
        "element": True,
        "quantity": False,
        "material_type": False,
        "designation": True,
        "material_subtype": True,
        "width": False,
        "height": False,
        "length": False,
        "usage_quantity": True,
        "finish_quantity": True,
        "additional_info": True,
    },
    "secondary": {},
}


NUMERIC_AS_STRING_COLUMNS = {
    "primary": [
        "part_tag",
    ],
    "secondary": [],
}


EXPECTED_DTYPES_CLEANING = {
    "primary": {
        "element": "string",
        "quantity": "int",
        "part_tag": "string",
        "material_type": "string",
        "designation": "string",
        "material_subtype": "string",
        "width": "int",
        "height": "int",
        "length": "int",
        "additional_info": "string",
        "usage_quantity": "float",
        "finish_quantity": "float",
    },
    "secondary": {},
}

REQUIRED_SQL_COLUMNS = {
    "primary": [
        "pon",
        "part_tag",
        "quantity",
        "material_category",
        "material_type",
        "material_subtype",
        "height",
        "width",
        "length",
        "usage_quantity",
        "finish_quantity",
        "designation",
        "element",
        "additional_info",
        "load_method",
        "snapshot_time_utc",
        "bom_filename",
        "uploaded_by",
    ],
    "secondary": [],
}
