TRUNCATE TABLE bom_schema.example_bom_final_current;

INSERT INTO bom_schema.example_bom_final_current
	([pon]
      ,[part_tag]
      ,[quantity]
      ,[material_category]
      ,[material_type]
      ,[material_subtype]
      ,[height]
      ,[width]
      ,[length]
      ,[usage_quantity]
      ,[finish_quantity]
      ,[designation]
      ,[element]
      ,[additional_info]
      ,[load_method]
      ,[snapshot_time_utc]
      ,[bom_filename]
      ,[uploaded_by]
      ,[item_id]
      ,[material_status]
      ,[is_item_unmatched])
SELECT [pon]
      ,[part_tag]
      ,[quantity]
      ,[material_category]
      ,[material_type]
      ,[material_subtype]
      ,[height]
      ,[width]
      ,[length]
      ,[usage_quantity]
      ,[finish_quantity]
      ,[designation]
      ,[element]
      ,[additional_info]
      ,[load_method]
      ,[snapshot_time_utc]
      ,[bom_filename]
      ,[uploaded_by]
      ,[item_id]
      ,[material_status]
      ,[is_item_unmatched]
FROM bom_schema.vw_example_bom_final_current;